### ISSUE TITLE
Model instance methods broken with sails 0.12.3

### ISSUE THREAD

**Issue by misterjt** [tjwebb/marlinspike#4]
I have payment system marlinspike hook. In this hook i have model `User.js`.

``` js
module.exports={
    attributes:{
        balance     : {
            type:'integer',
            defaultsTo:0
        },
        getBalance:function(){
            return this.balance/sails.config['paymentsystem'].currency_factor||0;
        },
        getFormatedBalance:function () {
            return String(this.getBalance()).replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g, '$1 ');
        }
    }
}
```

Since sails 0.12.3 i can not call getBalance or getFormatedBalance or any other model method from my parent app.

**Comment by tjwebb** [comment]
Can you track down the issue? Does it work with Sails 0.12.2?

**Comment by dilame** [comment]
It is broken since sails 0.12.2. 
So, the last sails release, that marlinspike works with is 0.12.1

**Comment by tjwebb** [comment]
PR would be helpful. We stopped maintaining all Sails-related modules in 2015. 

see https://github.com/tjwebb/marlinspike/issues/3
